name: Update videos.json

on:
  repository_dispatch:
    types: [update_videos]

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GH_TOKEN }}

      - name: Update videos.json
        run: |
          echo '${{ github.event.client_payload.data }}' > videos.json

      - name: Commit & Push
        run: |
          git config user.name "auto-admin"
          git config user.email "admin@bot.local"
          git add videos.json
          git commit -m "Update videos.json from admin panel"
          git push
