name: Update Videos JSON

on:
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Update videos.json
        run: |
          cp admin/input.json videos.json

      - name: Commit & Push
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add videos.json
          git commit -m "Auto update videos.json" || echo "No changes"
          git push
